https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/description/
https://leetcode.com/problems/sum-of-distances/
https://leetcode.com/problems/super-pow/description/
https://leetcode.com/problems/count-the-number-of-arrays-with-k-matching-adjacent-elements/description/
https://leetcode.com/problems/count-collisions-of-monkeys-on-a-polygon/description/
https://leetcode.com/problems/rotate-list/
https://algo.monster/liteproblems/186
https://leetcode.com/problems/make-k-subarray-sums-equal/
https://leetcode.com/problems/lexicographical-numbers/?envType=daily-question&envId=2025-06-08
https://leetcode.com/problems/lexicographically-minimum-string-after-removing-stars/description/?envType=daily-question&envId=2025-06-07
https://algo.monster/liteproblems/3400
https://leetcode.com/problems/check-if-a-parentheses-string-can-be-valid/description/
https://github.com/MAZHARMIK/Cpp-STL-Quick-Help
https://leetcode.com/problems/maximum-alternating-subsequence-sum/
https://leetcode.com/problems/longest-increasing-subsequence/
https://leetcode.com/problems/detonate-the-maximum-bombs/
https://leetcode.com/problems/find-the-largest-almost-missing-integer/description/
https://leetcode.com/problems/battleships-in-a-board/description/
https://leetcode.com/problems/count-number-of-maximum-bitwise-or-subsets/description/
https://leetcode.com/problems/find-unique-binary-string/description/
https://leetcode.com/problems/count-number-of-maximum-bitwise-or-subsets/description/
https://leetcode.com/problems/letter-case-permutation/description/
https://leetcode.com/problems/combination-sum/
https://leetcode.com/problems/combination-sum-ii/description/
https://leetcode.com/problems/combination-sum-iii/
https://leetcode.com/problems/combination-sum-iv/
https://leetcode.com/problems/permutations/
https://leetcode.com/problems/maximum-length-of-pair-chain/description/
https://leetcode.com/problems/longest-string-chain/description/
https://leetcode.com/problems/flood-fill/description/ 
https://leetcode.com/problems/island-perimeter/description/
https://leetcode.com/problems/rotting-oranges/description/
https://leetcode.com/problems/escape-the-spreading-fire/description/
https://leetcode.com/problems/find-array-given-subset-sums/description/
https://leetcode.com/problems/walls-and-gates/description/
https://leetcode.com/problems/the-number-of-ways-to-make-the-sum/description/
https://leetcode.com/problems/generalized-abbreviation/description/
https://leetcode.com/problems/factor-combinations/description/
https://www.geeksforgeeks.org/problems/coin-change2448/1
https://leetcode.ca/2024-06-22-3183-The-Number-of-Ways-to-Make-the-Sum/
https://leetcode.com/problems/trapping-rain-water/description/
https://leetcode.com/problems/container-with-most-water/description/
https://leetcode.com/problems/product-of-array-except-self/description/
https://leetcode.com/problems/trapping-rain-water-ii/description/
https://leetcode.com/problems/maximum-value-of-an-ordered-triplet-ii/description/
https://leetcode.com/problems/minimize-the-maximum-difference-of-pairs/description/?envType=daily-question&envId=2025-06-13asd
https://www.geeksforgeeks.org/problems/equal-0-1-and-23208/1
https://leetcode.com/problems/maximum-length-of-a-concatenated-string-with-unique-characters/description/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-v/description/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/description/
https://leetcode.com/problems/minimize-maximum-of-array/
https://leetcode.com/problems/maximum-value-at-a-given-index-in-a-bounded-array/
https://leetcode.com/problems/sum-of-beauty-in-the-array/description/
https://www.geeksforgeeks.org/problems/equal-0-1-and-23208/1
https://leetcode.com/problems/count-of-substrings-containing-every-vowel-and-k-consonants-ii/?envType=daily-question&envId=2025-03-10
https://leetcode.com/problems/maximum-difference-by-remapping-a-digit/?envType=daily-question&envId=2025-06-1
https://leetcode.com/problems/count-of-substrings-containing-every-vowel-and-k-consonants-ii/description/?envType=daily-question&envId=2025-03-10
https://www.geeksforgeeks.org/problems/largest-subarray-of-0s-and-1s/1
https://www.geeksforgeeks.org/problems/count-subarrays-with-equal-number-of-1s-and-0s-1587115620/1
https://leetcode.com/problems/sum-of-beauty-in-the-array/description/
https://leetcode.com/problems/maximum-value-of-an-ordered-triplet-ii/
https://leetcode.com/problems/minimum-rounds-to-complete-all-tasks/description/
https://leetcode.com/problems/count-number-of-ways-to-place-houses/
https://leetcode.com/problems/number-of-ways-to-reach-a-position-after-exactly-k-steps/description/
https://leetcode.com/problems/count-ways-to-build-good-strings/description/
https://leetcode.com/problems/find-number-of-ways-to-reach-the-k-th-stair/description/
https://leetcode.com/problems/frog-jump-ii/description/
https://leetcode.com/problems/frog-jump/
https://leetcode.com/problems/frog-jump-ii/
https://leetcode.com/problems/house-robber-iii/description/
https://leetcode.com/problems/house-robber-iv/description/
https://leetcode.com/problems/mice-and-cheese/description/
https://leetcode.com/problems/divide-array-into-arrays-with-max-difference/description/?envType=daily-question&envId=2025-06-18
https://leetcode.com/problems/largest-element-in-an-array-after-merge-operations/description/
https://leetcode.com/problems/delete-and-earn/description/
https://leetcode.com/problems/minimum-sideway-jumps/description/
https://leetcode.com/problems/partition-array-such-that-maximum-difference-is-k/description/?envType=daily-question&envId=2025-06-19
https://leetcode.com/problems/maximum-number-of-points-from-grid-queries/description/
https://leetcode.com/problems/course-schedule/description/
https://leetcode.com/problems/course-schedule-ii/
https://leetcode.com/problems/course-schedule-iii/
https://leetcode.com/problems/wildcard-matching/
https://leetcode.com/problems/regular-expression-matching/description/
https://leetcode.com/problems/longest-substring-of-all-vowels-in-order/